"""Longdesc templates for randomly-spawned mobs, keyed by anatomy slot.

Two kinds of keys:

* Singular locations (``hair``, ``head``, ``face``, ``neck``, ``chest``,
  ``back``, ``abdomen``, ``groin``) — applied to that one location.
* Pair keys from ``PAIR_MERGE_KEYS`` (``eyes``, ``ears``, ``arms``,
  ``hands``, ``thighs``, ``shins``, ``feet``) — one entry is applied to
  *both* sides, so the renderer's paired-collapse path engages and the two
  sides render as a single plural line.

Token conventions:

* Pronouns: ``{their}`` / ``{they}`` / ``{them}`` / ``{themselves}`` and
  their capitalized variants resolve to the apparent gender at render time.
* Pair-slot nouns: brace ``{eyes}`` / ``{ears}`` / ``{arms}`` / ``{hands}``
  / ``{thighs}`` / ``{shins}`` / ``{feet}`` so the renderer can singularize
  them if one side is lost. Any verb that must agree should also be braced
  (``{are}``, ``{move}``) — its plural form is authored, the renderer
  conjugates the singular when needed.

Add entries by appending to the relevant list; no registration step.
"""

from __future__ import annotations

LONGDESCS: dict[str, list[str]] = {
    # =====================================================================
    # HEAD REGION — singular locations
    # =====================================================================
    "hair": [
        "It hangs in {their} face in uneven strands that {they} keep not bothering to brush back.",
        "It is cropped close enough to suggest a recent decision rather than a style.",
        "It looks like it was last cut by {themselves}, in poor light, in a hurry.",
        "It carries the faint flat sheen of cheap colony shampoo.",
        "It is dry at the ends and oily at the roots, the kind of hair that resists conditioning.",
        "Stray flakes of something pale catch the light here and there.",
        "It is tied back functionally, the way a person ties hair back when they expect to be moving.",
        "The roots show a centimeter of a different color, telling on a recent cosmetic decision.",
        "It hangs limp around {their} ears, neither tidy nor a statement.",
        "There's a half-healed scrape visible along the scalp where the hairline gives way.",
        "A faint ring of static makes the shorter hairs stand on end.",
        "It is pulled tight against the skull, severe in a way that does the face no favors.",
        "One side is noticeably shorter than the other, as if {they} fell asleep on a fire.",
        "It is greying in a streak that suggests stress, not age.",
        "It has the slightly mineral stiffness that comes from washing in recycled water.",
        "A few strands have caught at the nape of {their} neck and stayed there.",
        "It has been combed exactly once today and not since.",
        "The colony's overhead lights pick out every individual strand unkindly.",
        "It frames {their} face in a way that seems deliberate and unflattering.",
        "It bears the dull cast of hair that has spent too many hours under unfiltered air.",
        "It bears the faint indentation of a hat that is no longer being worn.",
        "There's a streak of dust through it that {they} have not noticed yet.",
        "It is parted unevenly, as though by accident, and never corrected.",
        "It has the slightly brittle look of hair that has met too many chemicals.",
        "Wisps of it move when {they} move, never quite settling.",
        "It is gathered at the nape in a knot tied without ceremony.",
        "It looks slept-in, in a way that suggests {they} slept somewhere harder than a bed.",
        "There's a single piece of grit caught in it that catches the light.",
        "The colony's filtered air has done it no favors.",
        "It is thick enough at the temples to hide whatever {their} ears are doing.",
        "It clings to the back of {their} neck where sweat has dampened it.",
        "It has the unevenness of hair that's been growing out from something shorter.",
        "It falls forward whenever {they} look down and {they} keep pushing it back.",
        "It hangs in a slightly tangled coil at the nape that someone smoothed back hours ago.",
        "A few short hairs stick up at the crown in a permanent cowlick.",
        "It is matted in one small patch where something dried into it and was not fully washed out.",
        "It is braided in a tight, no-nonsense pattern that suggests practical concerns.",
        "There's a small piece of plastic — a clip, maybe — barely holding part of it in place.",
        "It is dusted lightly with what looks like ash, or just colony dust.",
        "It has the flat, freshly-shaved feel of having been buzzed down within the last day.",
        "It is fine and thin enough that the scalp shows through under the light.",
        "It hangs down past {their} jaw with no clear intention.",
    ],
    "head": [
        "{Their} head sits on {their} neck at a slight, considering angle.",
        "{Their} scalp shows the faint outline of an old impact scar above the temple.",
        "A small bald patch sits at the crown that looks accidental rather than chosen.",
        "The shape of {their} skull is plain under the skin, narrow and angular.",
        "A pale crescent scar runs along one side, neat enough to suggest medical work.",
        "{Their} head is held very still, as though motion costs something.",
        "There's a faint dent above one ear that nobody has ever explained to {them}.",
        "{Their} scalp glistens slightly with sweat that has nowhere to go.",
        "The skin at {their} temple twitches faintly with a slow, unconscious pulse.",
        "{Their} head turns in small, careful increments, as though tracking sound.",
        "A flat, smooth area at the back of the skull suggests a healed surgical access.",
        "{Their} forehead carries the etched horizontal lines of someone who frowns more than they smile.",
        "{Their} skull has the slightly heavy set of someone whose helmet has been worn too long, too often.",
        "There's a thin scar along the hairline that someone took the trouble to sew well.",
        "The crown of {their} head bears a faint, deliberate-looking implant access port.",
        "{Their} head tilts when {they} listen, as if one ear works better than the other.",
        "A small, faded data port sits flush behind one ear.",
        "{Their} head moves a beat after the rest of {them}, as if running on slight delay.",
        "There's a bruise just at the hairline, healing yellow-green.",
        "The cant of {their} head is slightly off vertical, in a way that suggests an old neck injury.",
        "A pale band of skin at the brow tells of safety glasses that were worn for years.",
        "{Their} head holds steady, eyes moving instead — the discipline of someone who's been trained.",
        "A faint indentation circles {their} crown where something tight used to be.",
        "{Their} skull narrows toward the back in a way the light catches.",
        "The skin across {their} forehead is dry, faintly flaking.",
        "{Their} head sits on {their} shoulders like it has been deliberately balanced.",
        "There's a healed laceration above one eyebrow that did not close well.",
        "{Their} scalp is faintly oily where the hair parts.",
        "A small irregularity at the temple suggests something is implanted just under the skin.",
        "{Their} head jerks faintly at small sounds, then catches itself.",
        "An old burn scar fans across the side of {their} head, hairless and pink.",
        "The base of {their} skull bears the faint shadow of a tattoo that's been laser-faded.",
        "{Their} head sits forward of {their} shoulders, as though leaning toward something to hear.",
        "{Their} crown is flat in profile, the shape that long sleep on hard surfaces produces.",
        "A streak of pale skin runs from temple to ear, the legacy of a long-healed cut.",
        "{Their} head has the heaviness of someone fighting a low-grade hangover.",
        "{Their} head is shaved in a single careful strip down the center of the scalp.",
        "There's a small dark birthmark at the temple, irregular and old.",
        "{Their} skull is faintly asymmetric, one side broader than the other.",
        "{Their} head rests at the precarious angle of someone almost falling asleep where they stand.",
        "A small electrode-shaped pale spot sits behind one ear, an old diagnostic mark.",
    ],
    "face": [
        "{Their} face wears the slack neutrality of someone who has stopped performing expressions.",
        "{Their} cheeks are hollowed in a way that splits the difference between sculpted and underfed.",
        "A faded scar runs along {their} jawline, the kind that takes a season to lose its color.",
        "{Their} face is unevenly tanned, as though {they} usually wear something across half of it.",
        "There's a sheen of dried sweat on {their} brow that {they} have not yet wiped.",
        "{Their} mouth sits in a permanent, faint frown that does not seem to involve emotion.",
        "{Their} jaw is set in the way that people who grind their teeth set their jaws.",
        "{Their} cheekbones are high enough to put faint shadows under them in the colony lighting.",
        "A small, pale freckle sits near the corner of {their} mouth — the kind of mark people notice.",
        "{Their} face shows the lines of someone who has spent significant time squinting into wind.",
        "{Their} lips are dry and slightly cracked in two parallel lines.",
        "{Their} chin is shadowed with the early stubble of someone who shaved a day or two ago.",
        "There's a faint discoloration high on one cheek that might be a healing bruise.",
        "{Their} face holds the unreadable, watchful stillness of someone who has learned not to be read.",
        "{Their} mouth twitches at the corners, as though biting back something every few seconds.",
        "A faded thin scar bisects {their} upper lip, neat enough to be cosmetic if intentional.",
        "{Their} cheeks bear the faint pitting of skin that healed badly from an old illness.",
        "{Their} jaw works slowly, as though chewing on the word {they} are about to say.",
        "{Their} skin has the matte texture of someone who has stopped caring about moisturizer.",
        "A thin film of grime traces the line of {their} hairline, never quite scrubbed away.",
        "{Their} brow stays slightly furrowed, as though everything requires a small effort of concentration.",
        "{Their} face turns slowly toward whoever speaks, never quite first.",
        "There's a healed split in one eyebrow where the hair grows around a thin pale line.",
        "{Their} cheeks are flushed faintly red, in patches that suggest cold or alcohol.",
        "{Their} face wears the pale, slightly sweaty cast of someone fighting an illness {they} have not named.",
        "A long-faded tattoo curves along {their} jaw, illegible at this distance.",
        "{Their} expression sits between resignation and stubbornness, the look that gets a person through a long shift.",
        "{Their} face is freshly washed but not freshly rested — the cleanness is recent and superficial.",
        "{Their} cheeks bear the linear imprint of a recent nap against a rough surface.",
        "{Their} mouth holds a slight, ironic curve that does not quite become a smile.",
        "{Their} face moves in single units — eyes, then mouth, then jaw — never all at once.",
        "{Their} skin is flushed unevenly along one side of the jaw, the asymmetric pattern of poor circulation.",
        "There's a constellation of small old acne scars along one cheek.",
        "{Their} face wears the faintly waxen cast of someone who hasn't seen direct sun in a while.",
        "{Their} expression does not change when others speak, the way a person waits out a stranger's pitch.",
        "{Their} jaw is faintly slack on one side, the legacy of an injury or a tic.",
        "{Their} mouth holds the shape of words {they} aren't speaking.",
        "A dark mole sits just under {their} eye, drawing attention by holding still.",
        "{Their} cheeks suck in slightly when {they} concentrate, hollowing further.",
        "There's a faint dusting of pale stubble across the jaw that catches the colony light.",
        "{Their} face has the unwashed sheen that comes from long hours under recycled air.",
        "{Their} mouth has the corners-down set of someone trying not to comment.",
    ],
    "neck": [
        "{Their} neck shows the faint horizontal line of a collar worn daily for years.",
        "A small, faded data port sits low on the side of {their} neck.",
        "The cords of {their} neck stand out faintly when {they} swallow.",
        "{Their} neck is long enough to be noticed, narrow enough to look fragile.",
        "There's a healed scar curving around the throat, the kind nobody wants to ask about.",
        "{Their} pulse is visible at the side of the throat, ticking slightly fast.",
        "A small dark tattoo — letters, or numbers — sits at the base of {their} neck.",
        "The skin under {their} jaw is loose enough to soften the line of the throat.",
        "{Their} neck bears a faint ring of dirt low at the throat that no recent washing has caught.",
        "There's a discoloration low on the throat that might be a bruise or a birthmark.",
        "{Their} neck is corded with the tension of someone who has not relaxed their shoulders in hours.",
        "{Their} neck bears a long faded scar that runs from behind the jaw to the collarbone.",
        "{Their} neck is sunburned in an irregular patch, the work of one bad day off-dome.",
        "{Their} throat moves visibly when {they} listen, swallowing too often.",
        "There's a small dark mole high on the throat that catches the light.",
        "{Their} neck is unusually thick at the base, the build of a wrestler or a yoke worker.",
        "{Their} carotid pulse is faintly visible, the slow rhythm of someone steady.",
        "A faded surgical line runs across the front of {their} throat, healed pale.",
        "{Their} neck is held stiffly, as if turning hurts.",
        "There's a faint indentation low on the throat where a fingertip would rest.",
        "{Their} neck tenses visibly every time {they} hear a sudden sound.",
        "A pale scar runs from behind one ear down the side of {their} throat.",
        "{Their} neck is freckled where it meets {their} collarbones, sun damage from years ago.",
        "The skin of {their} neck is flushed faintly red, as if {they} have been recently exerting {themselves}.",
        "{Their} throat moves through a slow, deliberate swallow as {they} settle their breath.",
        "There's a small mole at the side of {their} throat that catches the eye.",
        "{Their} neck looks strangely vulnerable, the sleeve's only unarmored part.",
        "{Their} neck bears the round mark of something that used to be pressed there habitually.",
        "{Their} throat carries a long pale scar that runs across the side, healed years ago.",
        "A small, dark birthmark sits low under one ear in an irregular shape.",
        "{Their} neck bears the long-faded outline of a tattoo that's been laser-treated nearly invisible.",
        "There's a faint asymmetry to {their} neck, one side fuller than the other.",
        "{Their} throat carries the loose set of a person who rarely tenses their jaw.",
        "{Their} neck holds the stillness of someone listening hard.",
        "A pale white scar circles {their} throat horizontally, neat as a line on a page.",
        "{Their} neck is dotted with faint, healed insect bites — colony fauna at work.",
        "{Their} throat bears a small, intentional brand low at the side, deliberate and old.",
        "There's a healed puncture scar low on the side of the neck, the kind that does not announce itself.",
        "{Their} neck is dusted faintly with the same grit that's on the rest of {them}.",
        "{Their} throat works visibly as {they} speak, like a slightly mistuned instrument.",
        "A line of stubble runs unevenly down one side of {their} neck where the razor missed.",
    ],
    # =====================================================================
    # TORSO REGION — singular locations
    # =====================================================================
    "chest": [
        "{Their} chest rises and falls in slow, careful breaths.",
        "The outline of an old injury shows in the way {their} chest sits, uneven across the sternum.",
        "{Their} chest holds the lean, slightly hollow build of long undereating.",
        "{Their} chest is broad enough to fill out whatever {they} are wearing without strain.",
        "A faint persistent rattle accompanies {their} breath, audible only if one listens.",
        "{Their} chest shows the slight asymmetry of an old fracture badly healed.",
        "{Their} breathing is shallow, the breath of someone conserving energy or hiding pain.",
        "{Their} chest is barrel-shaped, the build of someone who has done their share of heavy work.",
        "{Their} chest carries a faint scar where a long surgical drain once sat.",
        "{Their} chest is flat and small, the build of a sleeve that was probably underfed in development.",
        "{Their} chest is narrow, with the prominent collarbones of a small frame.",
        "{Their} chest holds the slight forward curve of someone who hunches over their work.",
        "{Their} chest carries the slight asymmetry of an old break that healed at its own pace.",
        "{Their} ribs press visibly against the skin on every inhale.",
        "There is a small, repeated motion in {their} chest, as if {they} are aware of their own heartbeat.",
        "{Their} chest moves smoothly, the easy mechanics of someone who has not yet been hit hard.",
        "{Their} chest holds the rounded softness of someone who used to be heavier.",
        "{Their} chest bears a small port closure low under the collarbone, years old.",
        "{Their} chest is dusted faintly with the same colony grit that's everywhere else.",
        "{Their} breathing speeds up briefly when {they} are looked at, then settles again.",
        "{Their} chest is sweat-damp in a way that has nothing to do with the temperature.",
        "There's a small protrusion at the sternum — old break, badly set — that the eye finds.",
        "{Their} chest bears a long thin scar low across the sternum, old and pale.",
        "{Their} chest moves in time with an internal rhythm slightly off the room's.",
        "{Their} chest skin carries the small yellowed cast of long-term smoking.",
        "{Their} chest holds the lean, hard build of someone who works for a living.",
        "{Their} chest skin bears the faint pale stripes where a harness has chronically pressed.",
        "{Their} chest looks deflated, as though {they} have not eaten properly in days.",
        "{Their} chest carries the slight forward roll of someone who works hunched over.",
        "There is a small, deliberate brand high on the upper chest, intentional and old.",
        "{Their} chest holds the kind of soft barrel that comes from long, easy years.",
        "{Their} chest bears the faint old shadow of a tattoo that has been laser-faded.",
        "{Their} chest carries the small, deliberate scar of a port closure low at the sternum.",
        "{Their} breathing hitches very slightly on every third inhale, a tic {they} no longer notice.",
        "{Their} chest moves out of sync with the rest of {them}, breath fast while limbs are still.",
        "{Their} chest holds the slight pectoral broadness of someone whose work involves pulling.",
        "A thin pale scar runs vertically down the center of {their} sternum, surgical and old.",
        "{Their} chest carries a small puncture scar low on one side, the size of a finger.",
        "{Their} chest carries a healed surgical access scar low and to one side.",
        "{Their} chest holds the perfectly average build of someone genetically undistinguished.",
        "{Their} chest holds the slight slack of a sleeve well into middle years.",
    ],
    "back": [
        "{Their} back is hunched slightly, the cant of someone who has been bent over a workstation too long.",
        "A long, narrow scar runs diagonally across {their} upper back, the legacy of a single bad cut.",
        "{Their} back is broad enough to give them a slight wedge silhouette.",
        "{Their} posture suggests an old injury that has never been fully addressed.",
        "{Their} back is straight in a way that suggests training rather than nature.",
        "{Their} shoulders pull forward subtly, a chronic posture they no longer notice.",
        "Bony shoulder blades stand out sharply, with every motion making them ripple.",
        "{Their} back is wide and faintly soft, the build of someone settling into middle years.",
        "There's a permanent slight curve to {their} spine that suggests scoliosis.",
        "{Their} back rises and falls visibly with breaths that are deeper than they look from the front.",
        "A line of vertebrae stands out faintly down the center of {their} back.",
        "{Their} back is dotted with faint, faded freckles across the upper shoulders.",
        "{Their} shoulders are squared with the deliberate effort of someone who was told to stand straight.",
        "{Their} back is dusted faintly with what looks like ash or fine soot.",
        "{Their} spine sits visibly crooked, a misalignment that draws the eye.",
        "There's a strip of pale skin along the lower back where chronic pressure has worn the same line.",
        "{Their} back is held tense, shoulders close to the ears in a steady half-flinch.",
        "{Their} back shows the unmistakable pressure marks of body armor recently removed.",
        "{Their} back is narrow, the build of someone who has stayed small on purpose.",
        "There's a healed knife scar low on the back, the kind that nicked but did not stop the lung.",
        "{Their} back moves with the loose, settled ease of someone with no immediate concerns.",
        "{Their} spine is rigidly straight, the bearing of someone who was trained to stand that way.",
        "{Their} back bears the faint outline of an old, large tattoo that runs from shoulder blade to shoulder blade.",
        "{Their} back curves into the chair or wall whenever there is something to lean against.",
        "{Their} shoulders roll slowly forward and back when {they} think no one is watching.",
        "{Their} back is faintly damp with sweat that has not yet had a chance to dry.",
        "There's a clear protrusion at the lower spine, the shape of an old impact that healed wrong.",
        "{Their} back is bare of any visible scars or marks, which itself feels noteworthy.",
        "{Their} back holds the broad, soft strength of someone who carries heavy things for a living.",
        "{Their} back bears the faint regular indentations of a chair {they} have spent too many hours in.",
        "There's a brand-shaped mark low on the back, healed but still raised against the skin.",
        "{Their} back hunches subtly forward whenever {they} talk, as if leaning into the conversation.",
        "{Their} back is straight enough to be slightly unnatural, the posture of professional bodyguards.",
        "{Their} shoulders carry the rolled-forward tension of someone whose neck hurts.",
        "{Their} back holds the slightly soft curve of someone whose work used to be physical and isn't anymore.",
        "{Their} back bears a constellation of small healed acne scars across the shoulders.",
        "There's a faint indentation between the shoulder blades that fingers want to find.",
        "{Their} back arches faintly with every deep breath, working out unseen tension.",
        "{Their} back wears the rumpled, slept-in cast of someone who passed out where they shouldn't have.",
        "{Their} back is faintly hairy at the shoulders, dense enough to catch the light.",
        "{Their} back bears a small faded brand between the shoulder blades.",
    ],
    "abdomen": [
        "{Their} abdomen is flat and tight, the build of someone who eats sparingly or works hard.",
        "{Their} stomach is faintly soft at the lower curve, in a way that suggests recent indulgence.",
        "{Their} abdomen carries the faint roundness of someone who has not been actively starving.",
        "A long, vertical scar runs down the center of {their} abdomen, the line of an old surgery.",
        "{Their} stomach moves visibly with each breath, sucked in and out.",
        "{Their} belly carries a relaxed, generous roundness with cheerful indifference.",
        "{Their} abdomen is concave enough to suggest several missed meals.",
        "{Their} stomach holds the rounded weight of a person comfortable with food.",
        "{Their} abdomen carries the muscular ridges of someone who exercises with intent.",
        "A faded vertical scar low on the belly suggests an old appendectomy or similar.",
        "{Their} stomach bears a long-faded surgical scar to one side of the navel.",
        "{Their} belly trembles slightly with the high-strung tension of someone who has not eaten today.",
        "{Their} abdomen is dusted with the same grit that lives on the rest of {them}.",
        "{Their} stomach bears the small, regular punctures of insulin or stim injection sites.",
        "{Their} belly carries a small protrusion off-center that catches the eye.",
        "{Their} abdomen tightens visibly when {they} are addressed.",
        "{Their} stomach holds the slack of someone who used to be heavier and recently isn't.",
        "{Their} belly is taut, the small drum of someone who has not had a proper bowel movement in days.",
        "{Their} abdomen carries a tattoo that runs down toward the hip, illegible at this distance.",
        "{Their} stomach is faintly burned along one side, the legacy of a chemical splash long healed.",
        "{Their} belly is uneven, soft on one side and tight on the other.",
        "{Their} abdomen shows the small, regular scars of a chronic medical condition.",
        "{Their} stomach is concave below the ribs in a way that draws the eye.",
        "{Their} belly bears the deep dimple of a navel piercing long since removed.",
        "{Their} abdomen is sleek with the kind of fitness that comes from regimented training.",
        "{Their} stomach growls faintly while {they} stand, the report of a long fast.",
        "{Their} belly is faintly distended, in a way that suggests a recent heavy meal.",
        "{Their} abdomen holds a faint sheen of sweat that catches the light unevenly.",
        "{Their} stomach bears a small healed knife scar just left of the navel.",
        "{Their} abdomen looks soft and untouched, the belly of someone who has never been hit hard.",
        "{Their} stomach carries the round shape of someone newly weight-trained.",
        "{Their} abdomen is taut and flat enough to suggest a recent weight cut.",
        "{Their} belly hangs heavy in a soft, comfortable swell.",
        "{Their} stomach bears the broad horizontal line of an old C-section scar.",
        "{Their} abdomen sucks in tight whenever {they} catch a stranger's eye.",
        "{Their} belly is firm and round, the abdominal pressure of long-term beer drinking.",
        "{Their} abdomen bears a faded port closure just above the navel.",
        "{Their} stomach is hollowed in a way that suggests both undereating and overworking.",
        "{Their} belly bears a smear of grease or something darker that {they} have not noticed.",
        "{Their} abdomen tightens and relaxes in a slow, deliberate rhythm — breathing exercises in public.",
        "{Their} belly bears a thin trail of dark hair running down from the navel.",
        "{Their} stomach sits in the slightly distended way that prolonged poor diet produces.",
    ],
    "groin": [
        "{Their} hips sit forward in the easy stance of someone who has nothing to protect.",
        "{Their} groin carries the small adjusted-tightness of someone who recently dressed for combat.",
        "{Their} hips hold an asymmetrical cant, one side higher than the other from old injury.",
        "{Their} groin is bandaged under the trousers, the outline barely visible.",
        "{Their} hips sit too narrow to be the build's natural shape, the legacy of years of underfeeding.",
        "{Their} groin moves with the deliberate slowness of someone managing chronic discomfort.",
        "{Their} hips carry the broad set of someone built for endurance work.",
        "{Their} pelvis tilts slightly forward as {they} stand, throwing the back into a faint arch.",
        "{Their} groin area is dusted with the universal colony grit.",
        "{Their} hips bear the faint outline of a holstered sidearm that is not currently present.",
        "{Their} groin sits stiffly, the bearing of someone with a recent injury they are not discussing.",
        "{Their} hips are angled in the slight twist of someone whose pelvis was broken and reset.",
        "{Their} groin area carries the faint smell of antiseptic that lingers after recent treatment.",
        "{Their} hips sway very faintly when {they} shift weight, a small unconscious motion.",
        "{Their} groin sits well-aligned, the easy balance of someone whose body works.",
        "{Their} hips bear a small implant scar low along the iliac crest, healed pale.",
        "{Their} pelvis tilts back slightly, the posture of someone trying not to look too eager.",
        "{Their} groin is held stiffly forward, in a way that draws attention to itself.",
        "{Their} hips carry the slight forward swing of someone who has been on their feet too long.",
        "{Their} pelvis bears the faint visible outline of an old surgical site through the trousers.",
        "{Their} groin area moves in time with {their} steps in the way of someone freshly out of physical therapy.",
        "{Their} hips are wide and steady, the structural foundation of a strong sleeve.",
        "{Their} pelvis sits in the faint forward thrust that comes from old back pain.",
        "{Their} groin carries the small dark spot of a port long since closed and faded.",
        "{Their} hips bear the bruise of a recent fall, fading yellow under the skin.",
        "{Their} pelvis holds itself with the slight protective curl of someone who has been kicked there recently.",
        "{Their} hips swing slightly when {they} walk, the gait of someone in no particular hurry.",
        "{Their} groin sits relaxed in the way of someone genuinely at ease.",
        "{Their} pelvis bears a small tattoo just visible over the waistband.",
        "{Their} hips carry the small tightness of someone fighting nerve pain.",
        "{Their} groin area is freshly washed, the cleanliness slightly out of step with the rest of {them}.",
        "{Their} hips sit square and stable, the bearing of a trained brawler.",
        "{Their} pelvis tilts forward into a chronic anterior tilt.",
        "{Their} groin bears the faint outline of a recent bandage adhesive square.",
        "{Their} hips bear stretch marks visible above the waistband, silver-pale.",
        "{Their} pelvis sits in the slightly torqued posture of someone with one leg slightly shorter than the other.",
        "{Their} groin area carries a faint chemical scent that suggests recent disinfectant exposure.",
        "{Their} hips bear the deep imprint of a holster belt worn for too many hours.",
        "{Their} pelvis is small and narrow under loose clothing.",
        "{Their} groin carries the small old scar of a piercing site long since closed.",
        "{Their} hips bear the faint outline of armor that is no longer being worn.",
    ],
    # =====================================================================
    # PAIRED LOCATIONS — use pair-key entries
    # =====================================================================
    "eyes": [
        "{Their} {eyes} are an unremarkable brown that meet a stranger's gaze without comment.",
        "{Their} {eyes} are pale enough that the pupils stand out as sharp dark points.",
        "{Their} {eyes} hold the flat, careful neutrality of someone who has learned not to react.",
        "There's a faint redness at the rim of {their} {eyes} that suggests recent crying or recent stims.",
        "{Their} {eyes} are bright with the kind of alertness that comes from chemical assistance.",
        "{Their} {eyes} sit deep enough in {their} face to be perpetually shadowed.",
        "{Their} {eyes} carry the slow blink of someone in no particular hurry to focus.",
        "{Their} {eyes} are widely-spaced enough to give the face an open, slightly innocent look.",
        "{Their} {eyes} are close-set enough to make {them} look perpetually skeptical.",
        "{Their} {eyes} are dark to the point of looking almost black in the colony lighting.",
        "{Their} {eyes} are a startling pale grey that draws attention against the rest of the face.",
        "{Their} {eyes} carry the faint dilated quality of someone who has recently been in dim rooms.",
        "{Their} {eyes} dart toward sudden motion and then back, like a tic.",
        "{Their} {eyes} hold the steady, slightly out-of-focus look of someone listening to internal audio.",
        "A pale ring around {their} pupils suggests an optical implant in regular use.",
        "{Their} {eyes} are bloodshot enough to suggest a night without sleep.",
        "{Their} {eyes} have the slightly delayed blink of someone fighting fatigue.",
        "{Their} {eyes} are the same green-grey as old copper.",
        "{Their} {eyes} are a warm amber that catches the colony lights softly.",
        "{Their} {eyes} hold a faint perpetual squint that does not relax even in dim light.",
        "{Their} {eyes} move in small, precise saccades, scanning the room.",
        "There's a small flake of something pale caught at the corner of one eye.",
        "{Their} {eyes} are blue enough to be remarked on, in a face otherwise unremarkable.",
        "{Their} {eyes} have the slightly puffy quality of someone who slept very recently.",
        "{Their} {eyes} carry the deliberate stillness of someone who has trained {themselves} not to glance away.",
        "{Their} {eyes} are an unmatched pair — one slightly lighter than the other.",
        "{Their} {eyes} sit slightly asymmetrically, one higher than the other.",
        "{Their} {eyes} hold the faint wet sheen of someone fighting the urge to blink.",
        "{Their} {eyes} are framed by lashes thick enough to cast small shadows on the cheeks.",
        "{Their} {eyes} carry a thin film of moisture that catches the light.",
        "{Their} {eyes} are sharply defined by deep set crows-feet at the corners.",
        "{Their} {eyes} have the bright dilated quality of someone running on adrenaline.",
        "{Their} {eyes} are a soft hazel that shifts toward green in the colony lighting.",
        "{Their} {eyes} hold the perpetually-wet quality of allergies or grief or both.",
        "{Their} {eyes} have the matte quality of cataracts beginning to form.",
        "{Their} {eyes} hold the small ironic glint of someone who finds most of this funny.",
        "{Their} {eyes} dart over the room without seeming to see any of it.",
        "{Their} {eyes} hold steady on whatever they look at, with a quality that strangers find uncomfortable.",
        "{Their} {eyes} are slightly yellowed in the whites, the legacy of a chronic condition.",
        "{Their} {eyes} carry the slight glassiness of recent intoxication.",
        "{Their} {eyes} hold a faint reflective ring of an active optic implant.",
        "{Their} {eyes} are a striking violet that the lighting cannot quite explain.",
    ],
    "ears": [
        "{Their} {ears} are small and tight against the skull, faintly translucent at the edges.",
        "{Their} {ears} carry the faint flush of cold or embarrassment.",
        "{Their} {ears} bear small clean piercing holes through the lobes, currently empty.",
        "{Their} {ears} are larger than the rest of the face would suggest.",
        "There's a faint healed split along the lobe of {their} {ears} where piercings used to be.",
        "{Their} {ears} bear the small, hard scar tissue of someone who has had cauliflower ear treated.",
        "{Their} {ears} sit asymmetrically against the head, one slightly higher than the other.",
        "{Their} {ears} are pierced multiple times along the cartilage, the holes mostly empty now.",
        "{Their} {ears} bear faint pale outlines where headphones or comms gear has rested for years.",
        "A small data port nestles behind the curve of {their} {ears}.",
        "{Their} {ears} carry the small flake-edges of dry skin that won't quite resolve.",
        "{Their} {ears} bear a single matched pair of healed lobe piercings, modest and uniform.",
        "{Their} {ears} stick out from the head at a slight angle, giving {them} a faintly alert look.",
        "{Their} {ears} are flushed pink at the rim, the colony temperature notwithstanding.",
        "{Their} {ears} have the slightly torn-and-healed look of long-ago bar fights.",
        "{Their} {ears} carry small healed scars along the cartilage where someone bit or struck them.",
        "{Their} {ears} are tipped with the faint hair of a sleeve that grows facial hair early.",
        "{Their} {ears} bear the indentation of recent headphone use.",
        "{Their} {ears} are sleek and small, set close to a narrow skull.",
        "{Their} {ears} bear a row of tiny stud holes along the cartilage, abandoned.",
        "{Their} {ears} carry the faint sheen of a recently-cleaned hearing implant.",
        "{Their} {ears} bear the small protrusion of an under-skin earpiece.",
        "{Their} {ears} are reddened from cold despite the controlled colony temperature.",
        "{Their} {ears} bear faint healed holes where piercings once sat, now closed over.",
        "There's a small dark mole on the lobe of one ear that draws the eye.",
        "{Their} {ears} carry the visible scar of an old surgical access behind the lobe.",
        "{Their} {ears} are framed by hair just long enough to half-conceal them.",
        "{Their} {ears} bear heavily stretched lobes from long-term gauge wear, currently empty.",
        "{Their} {ears} sit close enough to the skull to be easily missed.",
        "{Their} {ears} bear a single piercing each, healed long ago and now bare.",
        "{Their} {ears} turn faintly when there's an unexpected sound, like an animal's.",
        "{Their} {ears} are clean and uncluttered, in a way that suggests deliberate grooming.",
        "{Their} {ears} bear a small healed nick on the lobe of each, faded white.",
        "{Their} {ears} carry the soft fine hair of a sleeve newly emerged from the tank.",
        "{Their} {ears} have a faint asymmetry, one rounder and one more pointed.",
        "{Their} {ears} bear the faint pucker of healed frostbite damage.",
        "{Their} {ears} carry small, almost invisible implant studs, visible only on close look.",
        "{Their} {ears} bear the small bumps of old keloid scars from previous piercings.",
        "{Their} {ears} carry the slightly cauliflowered thickening of someone who used to fight regularly.",
        "{Their} {ears} are remarkably small, almost vestigial-looking against the head.",
        "{Their} {ears} bear a single tiny piercing high on the cartilage of each side.",
        "{Their} {ears} are perpetually a shade redder than the rest of the face.",
    ],
    "arms": [
        "{Their} {arms} hang loose at {their} sides, ending in hands that are never quite still.",
        "{Their} {arms} are corded with the lean muscle of someone whose work is physical.",
        "{Their} {arms} bear the faded lines of old tattoos, ink that has begun to spread under the skin.",
        "{Their} {arms} are pale enough to suggest long indoor work, mottled with old bruises.",
        "{Their} {arms} are heavy with muscle and dotted with small healed cuts.",
        "{Their} {arms} bear a constellation of small round burn marks on the inside.",
        "{Their} {arms} are slender to the point of looking fragile, the wrists narrow.",
        "{Their} {arms} bear the small healed punctures of regular injection sites.",
        "{Their} {arms} are dusted with fine pale hair that catches the colony light.",
        "{Their} {arms} are wiry, with the kind of muscle that comes from hauling rather than lifting.",
        "{Their} {arms} bear the faint visible track of veins close to the surface.",
        "{Their} {arms} are heavy with a sleeper's softness, untrained but solid.",
        "{Their} {arms} carry a faint sheen of sweat that has dried in patches.",
        "{Their} {arms} bear the small mottled bruises of someone who bruises easily.",
        "{Their} {arms} are scarred at the forearms with the small healed cuts of self-harm long past.",
        "{Their} {arms} bear a deep healed scar on one bicep, the kind from a long-ago laceration.",
        "{Their} {arms} are sleeved in tattoos so dense it is hard to see skin between them.",
        "{Their} {arms} bear the faded ghost of full sleeves laser-faded down to shadow.",
        "{Their} {arms} are dotted with small dark moles in a constellation across the shoulders.",
        "{Their} {arms} bear the deep callus of someone who grips tools for a living.",
        "{Their} {arms} are scratched at the forearms with the small marks of working in tight spaces.",
        "{Their} {arms} carry the deep tan of someone who works outside the dome regularly.",
        "{Their} {arms} are corded with veins that stand out under the skin.",
        "{Their} {arms} hang slightly bent, the arms of someone who carries weight habitually.",
        "{Their} {arms} bear the small scars of an old harness chafing in the same place too many times.",
        "{Their} {arms} are dotted with the faded marks of an old skin condition.",
        "{Their} {arms} are unremarkable, the average build of a sleeve that has neither been trained nor wasted.",
        "{Their} {arms} bear surgical scars at the elbows, the legacy of joint repair.",
        "{Their} {arms} are pale and freckled, the freckles densest at the inner forearm.",
        "{Their} {arms} carry small healed marks at the crook of each elbow from years of blood work.",
        "{Their} {arms} are streaked with grease or grime that has not yet been washed off.",
        "{Their} {arms} bear the faintest crosshatch of fine surgical scars at the wrists.",
        "{Their} {arms} carry the deep golden tan of regular dome-side work.",
        "{Their} {arms} bear a long-faded pale mark on one forearm in the shape of a hand-grip.",
        "{Their} {arms} are surprisingly soft, in a way that the rest of the body does not match.",
        "{Their} {arms} bear small thin scars along the forearms, the marks of old defensive work.",
        "{Their} {arms} are heavy with implant scars at both shoulders, the marks of cybernetic upgrades.",
        "{Their} {arms} bear a single old tattoo at the inner forearm — a date, a name, illegible at this distance.",
        "{Their} {arms} are speckled with the small flat moles of long sun exposure.",
        "{Their} {arms} bear the deep grooves of long-healed self-harm, faded to silver.",
        "{Their} {arms} hold a slight tremor at rest, faint but constant.",
        "{Their} {arms} carry the small healed punctures of insulin or stim injection in a rotating pattern.",
    ],
    "hands": [
        "{Their} {hands} bear the deep callus of long manual work, palms harder than the fingers.",
        "{Their} {hands} are slender and ringless, with the nails bitten down to the quick.",
        "{Their} {hands} carry small healed cuts across the knuckles, the long marks of habitual fighting.",
        "{Their} {hands} are stained around the nail beds with something dark — ink, grease, or worse.",
        "{Their} {hands} are pale and soft, in a way that draws attention against the rest of the body.",
        "{Their} {hands} are large and broad, with fingers that look slightly swollen at the joints.",
        "{Their} {hands} bear the faint visible track of veins prominent across the back.",
        "{Their} {hands} carry the small scarring of years of accidents in cramped spaces.",
        "{Their} {hands} are dotted with the small healed punctures of a chronic medical condition.",
        "{Their} {hands} bear small tattoos on the knuckles — letters, perhaps, or symbols.",
        "{Their} {hands} bear pale tan lines on every finger but the thumbs where rings have habitually sat.",
        "{Their} {hands} bear the small healed nicks of working with cheap tools.",
        "{Their} {hands} carry the deep golden tan of someone who works outside the dome.",
        "{Their} {hands} are dotted with small dark moles across the back.",
        "{Their} {hands} bear the deep cracked calluses of someone whose gloves stopped protecting long ago.",
        "{Their} {hands} carry the trembling motion of fine nerve damage.",
        "{Their} {hands} are soft and clean, in a way that suggests {they} have never worked with them.",
        "{Their} {hands} bear the small healed scars of fingers broken and badly set.",
        "{Their} {hands} are dyed faintly orange at the nails — nicotine or hair color, hard to tell.",
        "{Their} {hands} carry the careful stillness of someone fighting tremor.",
        "{Their} {hands} bear the kind of scars that come from broken bottles in close fights.",
        "{Their} {hands} are large and clumsy-looking but move with surprising precision.",
        "{Their} {hands} bear matching healed scars across the middle knuckle of each.",
        "{Their} {hands} are crossed in front of {them} in a small habitual gesture.",
        "{Their} {hands} carry the dark grime of someone who has been in machinery recently.",
        "{Their} {hands} bear the deep yellowing of long-term smoking on the index and middle fingers.",
        "{Their} {hands} are unusually clean, in a way that draws notice in a place like this.",
        "{Their} {hands} bear the broad knuckles of someone who has hit a great many things hard.",
        "{Their} {hands} are folded loosely, the easy posture of someone who is not threatened.",
        "{Their} {hands} carry the dry, papery feel of someone whose work involves chemicals.",
        "{Their} {hands} bear small implant scars in the palms, neat and surgical.",
        "{Their} {hands} are gripping each other tightly, as though to keep them from doing something.",
        "{Their} {hands} bear the visible damage of having been broken and reset more than once.",
        "{Their} {hands} carry the trembling lightness of caffeine overload.",
        "{Their} {hands} bear faint smears of grease across the backs and into the fingers.",
        "{Their} {hands} are dotted with old scars and small healed nicks in roughly equal measure.",
        "{Their} {hands} bear the kind of calluses that develop on a person who handles ropes or cables.",
        "{Their} {hands} carry a slight permanent tan line where a wrist device used to sit.",
        "{Their} {hands} bear the small healed punctures of regular blood draws.",
        "{Their} {hands} bear the dry, papery skin of someone whose hands have been washed too often.",
        "{Their} {hands} are soft, with the manicured nails of someone with disposable income.",
        "{Their} {hands} bear thick calluses on the palms with surprisingly delicate fingers.",
    ],
    "thighs": [
        "{Their} {thighs} are heavy and muscular, the build of someone who walks long distances.",
        "{Their} {thighs} are thin enough that the bones of the iliac crest are sharply visible above them.",
        "{Their} {thighs} bear the deep pale stripes high on the inside where a holster has long pressed.",
        "{Their} {thighs} carry the deep ache of long shifts on hard surfaces.",
        "{Their} {thighs} are dusted with the universal colony grit.",
        "{Their} {thighs} bear the faded outline of an old surgical scar high on one side.",
        "{Their} {thighs} are heavy with the soft weight of someone who used to be active.",
        "{Their} {thighs} carry the easy lean strength of someone whose work involves walking.",
        "{Their} {thighs} bear the small healed puncture scars of regular intramuscular injections.",
        "{Their} {thighs} are narrow enough to draw the eye to the asymmetry between them.",
        "{Their} {thighs} are dotted with faded silver stretch marks across the outer side.",
        "{Their} {thighs} carry the well-muscled definition of regular weight training.",
        "{Their} {thighs} carry a sharp pale-and-tan boundary across the upper thigh.",
        "{Their} {thighs} bear an old tattoo on the outside, faded almost beyond legibility.",
        "{Their} {thighs} are dotted with small stretch marks that catch the light.",
        "{Their} {thighs} bear the small healed nicks of a long-ago dog attack.",
        "{Their} {thighs} carry the deep callus of someone who rides motor bikes regularly.",
        "{Their} {thighs} are soft and untoned, the legs of someone whose work is sedentary.",
        "{Their} {thighs} bear the deep skin-imprint of a holster worn through too many shifts.",
        "{Their} {thighs} are crossed habitually when {they} stand, knees touching.",
        "{Their} {thighs} bear the matching scars of someone who fell badly off something high.",
        "{Their} {thighs} carry the lean definition of a person who runs to clear their head.",
        "{Their} {thighs} are pale and unmarked, the legs of someone freshly sleeved.",
        "{Their} {thighs} bear a constellation of small old puncture scars from years of routine injection.",
        "{Their} {thighs} are dotted with silver stretch marks from old fast weight changes.",
        "{Their} {thighs} carry the small healed bites of a long-ago animal attack.",
        "{Their} {thighs} bear the dense muscle of regular squatting.",
        "{Their} {thighs} bear the long pale lines of healed surgical work high on the outside.",
        "{Their} {thighs} bear the small faded marks of years of bumping against hard edges.",
        "{Their} {thighs} bear the deep scars of an old serious accident.",
        "{Their} {thighs} are surprisingly soft, the skin smoother than the rest of the body.",
        "{Their} {thighs} carry the heavy thigh of someone who has been doing nothing but walking.",
        "{Their} {thighs} bear the small abraded scars of a knife sheath habitually worn against bare skin.",
        "{Their} {thighs} are smooth and hairless, in a way that is clearly intentional.",
        "{Their} {thighs} carry the hairiness of someone who has not bothered with grooming in months.",
        "{Their} {thighs} bear the long thick scar of a knife slash that closed badly.",
        "{Their} {thighs} are well-shaped from regular athletic activity.",
        "{Their} {thighs} carry a slight tremor of fatigue at rest.",
        "{Their} {thighs} bear the faint pale lines of healing stretch marks.",
        "{Their} {thighs} are scarred along the outside with the marks of an old burn.",
        "{Their} {thighs} carry the small puncture scars of an animal's claws.",
        "{Their} {thighs} bear deep calluses on the inner thigh from horseback riding or rough motorbike work.",
    ],
    "shins": [
        "{Their} {shins} are bare of any visible scars or marks, surprisingly clean for a sleeve this used.",
        "{Their} {shins} bear the small faded marks of years of walking into furniture.",
        "{Their} {shins} bear pale lines of old climbing scars along the bone.",
        "{Their} {shins} carry the faint horizontal scar of a long-ago shin splint resolved.",
        "{Their} {shins} bear a deep healed dent where an old blow didn't quite break the bone.",
        "{Their} {shins} are lined with a faint, wiry dark hair pattern.",
        "{Their} {shins} bear the small scars of years of careless work in low spaces.",
        "{Their} {shins} carry the deep gouge of a long-ago accident with industrial equipment.",
        "{Their} {shins} are heavy with thick muscle, broad at the calves.",
        "{Their} {shins} bear small healed scars in a regular pattern down the front.",
        "{Their} {shins} are dusted with the same fine grit that lives on the rest of the body.",
        "{Their} {shins} carry a long, dark old scar across the front of each.",
        "{Their} {shins} bear the matching round scars of insect-spider bites long healed.",
        "{Their} {shins} are remarkably hairy, in a way the rest of the body does not match.",
        "{Their} {shins} bear the small scratches of brushing against rough metal in cramped corridors.",
        "{Their} {shins} carry the small implant scar of an emergency med-port low on the leg.",
        "{Their} {shins} are pale and unmarked, the legs of someone who has not been walking long.",
        "{Their} {shins} bear the deep callus of someone who kneels on hard surfaces for a living.",
        "{Their} {shins} carry an old fracture line visible in the slight ridge of healed bone.",
        "{Their} {shins} bear small tattoos near the ankles — symbols or words.",
        "{Their} {shins} are lined with the small healed puncture scars of {their} job.",
        "{Their} {shins} bear the visible asymmetry of one leg being broken and reset.",
        "{Their} {shins} carry faded pale lines of old scrapes from years of falls.",
        "{Their} {shins} bear small smears of grease along the front, half-rubbed away.",
        "{Their} {shins} are soft and pale, untouched by the sun the rest of the body has met.",
        "{Their} {shins} bear the small scars of careless work with hand tools.",
        "{Their} {shins} carry a deep golden tan that ends sharply at the ankle.",
        "{Their} {shins} bear small faded scars from years of rough work.",
        "{Their} {shins} are lean and tight, defined by regular running.",
        "{Their} {shins} carry the small spider veins of someone on their feet too long.",
        "{Their} {shins} bear the small surgical scars of repair work after an old break.",
        "{Their} {shins} bear a long faint scar from ankle to knee on one side.",
        "{Their} {shins} bear small dark patches that look like healed burns.",
        "{Their} {shins} carry the small scratches of cat-tier urban wildlife.",
        "{Their} {shins} bear the matched scars of an old leg-iron worn too long.",
        "{Their} {shins} are pale at the front and bruised at the back from chronic bumping.",
        "{Their} {shins} carry the slight visible tremor of fatigue.",
        "{Their} {shins} bear small chemical burn scars from a long-ago industrial accident.",
        "{Their} {shins} are unmistakably swollen, suggesting circulation issues.",
        "{Their} {shins} bear small old healed scars on the front of each.",
        "{Their} {shins} carry the visible muscle definition of a runner.",
        "{Their} {shins} are dotted with the small healed bites of an old infestation.",
    ],
    "feet": [
        "{Their} {feet} are broad and flat, with toes splayed from years of standing shifts.",
        "{Their} {feet} look too small for the rest of the body, narrow and short.",
        "{Their} {feet} bear thick yellow calluses across the ball and heel.",
        "{Their} {feet} are flat and wide, the arches collapsed from decades of work.",
        "{Their} {feet} sit slightly turned in, the legacy of hips that have rotated over time.",
        "{Their} {feet} bear the high arches and prominent tendons of a runner.",
        "{Their} {feet} carry the slight outward flare of long-term overpronation.",
        "{Their} {feet} are visibly swollen, in a way that suggests chronic edema.",
        "{Their} {feet} bear the marks of long-ago frostbite damage in pale patches across the toes.",
        "{Their} {feet} look small and neat, with toes carefully aligned.",
        "{Their} {feet} bear the small careful steps of someone whose proprioception is half-rebuilt.",
        "{Their} {feet} sit splayed apart in the broad stance of a brawler.",
        "{Their} {feet} bear the broad span of someone with permanently spread arches.",
        "{Their} {feet} have toenails that are yellowed and slightly thickened.",
        "{Their} {feet} bear the curled-under toes of long-term shoe binding.",
        "{Their} {feet} have toes that splay outward, the toenails clean but cracked.",
        "{Their} {feet} bear the small healed scars of broken toes badly set.",
        "{Their} {feet} are dotted with the small dark moles of long sun exposure.",
        "{Their} {feet} bear thick callus along the outer edge of each sole.",
        "{Their} {feet} carry the heavy heel-strike of someone who walks like they mean it.",
        "{Their} {feet} bear the deep callus pattern of someone who runs barefoot on rough ground.",
        "{Their} {feet} have a noticeably hammered second toe on each side.",
        "{Their} {feet} bear thin pale scars across the tops from broken glass long ago.",
        "{Their} {feet} carry the deep golden tan of someone whose feet are usually exposed.",
        "{Their} {feet} are pale and unmarked, soft as a child's.",
        "{Their} {feet} bear long faded scars running from ankle to instep.",
        "{Their} {feet} bear the long-flattened arches of someone who took a hard hit there years ago.",
        "{Their} {feet} bear matching round scars on the tops, the marks of past surgical pins.",
        "{Their} {feet} have toenails clipped short and uneven.",
        "{Their} {feet} carry the slight tremor that comes with peripheral neuropathy.",
        "{Their} {feet} bear small healed lacerations between the toes from walking through something sharp.",
        "{Their} {feet} have a small healed surgical scar along the inside of one arch.",
        "{Their} {feet} carry the bunched, deformed look of bunions long unaddressed.",
        "{Their} {feet} are surprisingly dainty, the toes long and well-formed.",
        "{Their} {feet} have the slight outward toe-off of habitual ballet or dance training.",
        "{Their} {feet} bear the careful, precise placement of someone with damaged proprioception.",
        "{Their} {feet} carry the heavy tread of someone who has been on them all shift.",
        "{Their} {feet} bear the small faded marks of years of stubbing against hard edges.",
        "{Their} {feet} are dusted with the colony's universal grit between the toes.",
        "{Their} {feet} have a tattoo across the top of one — a date, a word, illegible from here.",
        "{Their} {feet} carry the careful tread of someone whose footing has been hard-won.",
        "{Their} {feet} bear the rough horny calluses of someone who walks barefoot by choice.",
    ],
}
