DEATH_SCROLL = [
    '||||||||||||||||||||| A red haze blurs your vision and the world slips away. ||||||||||||||||||||||',
    '||||||||||||||||||||| A red haze blurs your vision and the world slips away. ||||||||||||||||||||||',
    '||||||||||||||||||||| A red haze blurs your vision and the world slips away. || |||||||||||||||||||',
    '||||||||||||||||||||| A red haze blurs your vision and the w rld slips away. || |||||||||||||||||||',
    '||||||||||||||||||||| A re  haze blurs your vision and the w rld slips away. || |||||||||||||||||||',
    '||||||||||||||||||||| A re  haze blurs your v sion and the w rld slips away. || |||||||||||||||||||',
    '||||||||||| ||||||||| A re  haze blurs your v sion and the w rld slips away. || |||||||||||||||||||',
    '||||||||||| ||||||||| A re  haze blurs your v sion and the w rld slips away. |  |||||||||||||||||||',
    '||||||||||| ||||||||| A re  haze blurs your v sion a d the w rld slips away. |  |||||||||||||||||||',
    '||||||||||| ||||||||| A re  haze blurs your v sion a d the w rld slips away. |  || ||||||||||||||||',
    '||||||||||| ||||||||  A re  haze blurs your v sion a d the w rld slips away. |  || ||||||||||||||||',
    '||||||||||| ||||||||  A re  haze blurs your v sion a d the w rld slips away. |  || ||||||||||||||| ',
    '||||||||||| ||||||||  A re  haze blurs your v sion a d  he w rld slips away. |  || ||||||||||||||| ',
    '||||||||||  ||||||||  A re  haze blurs your v sion a d  he w rld slips away. |  || ||||||||||||||| ',
    '||||||||||  ||||||||  A re  haze blurs your v s on a d  he w rld slips away. |  || ||||||||||||||| ',
    '||||||||||  ||||||||  A re  haze blurs your v s on a d  he w r d slips away. |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs your v s on a d  he w r d slips away. |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs your v s on a d  he w r d sl ps away. |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs your v s on a d  he w r d sl p  away. |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs your v s on a d  he w r d sl p  awa . |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs your v   on a d  he w r d sl p  awa . |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs  our v   on a d  he w r d sl p  awa . |  || ||||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs  our v   on a d  he w r d sl p  awa . |  ||  |||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs  our v   on a d  he w r d sl p  a a . |  ||  |||||||||||||| ',
    '| ||||||||  ||||||||  A re  haze blurs  our v   on a d  he w r d sl p  a a . |  ||  |||||||| ||||| ',
    '| ||||||||  ||||| ||  A re  haze blurs  our v   on a d  he w r d sl p  a a . |  ||  |||||||| ||||| ',
    '| ||||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d sl p  a a . |  ||  |||||||| ||||| ',
    '| | ||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d sl p  a a . |  ||  |||||||| ||||| ',
    '| | ||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d s  p  a a . |  ||  |||||||| ||||| ',
    '| | ||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d s     a a . |  ||  |||||||| ||||| ',
    '| | ||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d s     a a . |  |',
    '| | ||||||  ||| | ||  A re  haze blurs  our v   on a d  he w r d s     a a . |  ||  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r d s     a a . |  ||  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r d s     a a . |  ||  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r   s     a a . |  ||  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r   s     a a . |   |  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r   s     a a . |   |  |||||||| ||| | ',
    '| | ||||||  ||| | ||  A re  h ze blurs  our v   on a d  he w r   s     a   . |   |  |||||||| ||| | ',
    '| | ||||||  ||| |  |  A re  h ze blurs  our v   on a d  he w r   s     a   . |   |  |||||||| ||| | ',
    '| | ||||||  ||| |  |  A re  h ze blurs  our v   on a d  he w r   s     a   . |   |  |||||||| ||| | ',
    '| | ||||||  ||| |  |  A re  h ze blurs  our v   on a d  he w r   s     a   . |   |  || ||||| ||| | ',
    '| | ||||||  |||    |  A re  h ze blurs  our v   on a d  he w r   s     a   . |   |  || ||||| ||| | ',
    '| | ||||||  |||    |  A re  h ze blurs  our v   on a d  he w r   s     a     |   |  || ||||| ||| | ',
    '| |  |||||  |||    |  A re  h ze blurs  our v   on a d  he w r   s     a     |   |  || ||||| ||| | ',
    '| |  |||||  |||    |  A re  h ze blurs  our v   on a d  he w r   s     a     |   |  || ||||| ||| | ',
    '|    |||||  |||    |  A re  h ze blurs  our v   on a d  he w r   s     a     |   |  || ||||| ||| | ',
    '|    |||||  |||    |  A re  h ze blur   our v   on a d  he w r   s     a     |   |  || ||||| ||| | ',
    '|    |||||  |||    |  A re  h ze blur   our v   on a d  he w r   s     a     |   |   | ||||| ||| | ',
    '|    |||||  |||    |  A re  h ze blur   our v   on a    he w r   s     a     |   |   | ||||| ||| | ',
    '|    |||||  |||    |  A re  h ze blur   our v   on a    he w r   s     a         |   | ||||| ||| | ',
    '     |||||  |||    |  A re  h ze blur   our v   on a    he w r   s     a         |   | ||||| ||| | ',
    '     |||||  ||     |  A re  h ze blur   our v   on a    h',
    '     |||||  ||     |  A re  h ze blur   our v   on a    he w r   s     a         |   | ||||| ||| | ',
    '     |||||  ||     |  A re  h ze blu    our v   on a    he w r   s     a         |   | ||||| ||| | ',
    '     |||||  |      |  A re  h ze blu    our v   on a    he w r   s     a         |   | ||||| ||| | ',
    '     |||||  |      |  A re  h ze blu    our v   on a    he w r   s     a         |   | | ||| ||| | ',
    '     |||||  |      |  A re  h ze bl     our v   on a    he w r   s     a         |   | | ||| ||| | ',
    '     |||||  |      |  A re  h  e bl     our v   on a    he w r   s     a         |   | | ||| ||| | ',
    '     |||||         |  A re  h  e bl     our v   on a    he w r   s     a         |   | | ||| ||| | ',
    '     |||||         |  A re  h  e bl     our v   on a    he w r   s     a         |   | | | | ||| | ',
    '     |||||         |  A re  h  e bl     our v    n a    he w r   s     a         |   | | | | ||| | ',
    '     |||||         |  A re  h  e bl     our v    n a    he w r   s     a         |   | | | |  || | ',
    '     |||||         |  A re  h  e bl     our v    n      he w r   s     a         |   | | | |  || | ',
    '     |||||         |  A re  h  e bl     our v    n      he w r   s     a         |   | | | |  || | ',
    '     |||||         |  A re  h  e bl     our v    n      he w r   s     a         |   | | | |  || | ',
    '     |||||         |  A re  h  e bl     our v    n      he w r   s     a             | | | |  || | ',
    '      ||||         |  A re  h  e bl     our v    n      he w r   s     a             | | | |  || | ',
    '      ||||         |  A re  h  e bl     our v    n      he w r   s     a             | | | |   | | ',
    '      ||||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   | | ',
    '      ||||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   | | ',
    '       |||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   | | ',
    '       |||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   | | ',
    '       |||         |  A re  h  e',
    '       |||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   |   ',
    '       |||         |  A re  h  e bl      ur v    n      he w r   s     a             | | | |   |   ',
    '       |||         |  A re  h  e bl      ur      n      he w r   s     a             | | | |   |   ',
    '       | |         |  A re  h  e bl      ur      n      he w r   s     a             | | | |   |   ',
    '       | |         |  A r   h  e bl      ur      n      he w r   s     a             | | | |   |   ',
    '       | |         |  A r   h  e bl      ur             he w r   s     a             | | | |   |   ',
    '         |         |  A r   h  e bl      ur             he w r   s     a             | | | |   |   ',
    '         |         |  A r   h  e  l      ur             he w r   s     a             | | | |   |   ',
    '         |         |  A r      e  l      ur             he w r   s     a             | | | |   |   ',
    '         |         |  A r      e  l      ur             he w r   s     a             |   | |   |   ',
    '         |         |  A r      e  l      ur             he w r   s     a             |   | |   |   ',
    '         |         |  A r      e  l      ur             he w r         a             |   | |   |   ',
    '                   |  A r      e  l      ur             he w r         a             |   | |   |   ',
    '                      A r      e  l      ur             he w r         a             |   | |   |   ',
    '                      A r      e  l      u              he w r         a             |   | |   |   ',
    '                      A r      e  l      u              h  w r         a             |   | |   |   ',
    '                      A r      e         u              h  w r         a             |   | |   |   ',
    '                      A r      e         u              h  w           a             |   | |   |   ',
    '                      A r                u              h  w           a             |   | |   |   ',
    '                      A r                u              h              a             |   | |   |   ',
    '                      A r',
    '                      A r                u                             a             |   | |   |   ',
    '                      A r                u                                           |   | |   |   ',
    '                      A r                u                                           |     |   |   ',
    '                      A r                u                                           |     |       ',
    '                      A r                u                                           |     |       ',
    '                      A r                                                            |     |       ',
    '                      A                                                              |     |       ',
    '                      A                                                              |     |       ',
    '                      A                                                                    |       ',
    '                                                                                           |       ',
    '||||||||||||||||||||| A red',
    '||||||||||||||||||||| A red haze blurs your vision and the world slips away. ||||||||||||||||||||||',
]